### ISSUE TITLE
Error warning for something that it's not an error.

### ISSUE THREAD

**Issue by janaxhell** [TheCaptain989/lidarr-flac2mp3#32]
I have just delpoyed https://github.com/RandomNinjaAtk/docker-lidarr-extended which is a standard Lidarr + AMD/AMVD scripts included to download via Deemix/Youtube. I've added flac2mp3 and it just works fine. Nevertheless lidarr-extended log says:

`[Error] flac2mp3-debug-2.sh: Debug|Enabling debug logging level 2. Starting AlbumDownload run. 
[Info] RefreshArtistService: Updating Info for Sam Sparro 
[Info] RefreshAlbumService: Updating Info for Return To Paradise 
[Info] RefreshAlbumService: Updating Info for Sam Sparro 
[Error] flac2mp3-debug-2.sh: Warn|Lidarr job ID 171387 timed out or failed. 
`

and flac2mp3.txt says
https://pastebin.com/kdVuSJW0

but it works. I just wanted to notify about this weird error message for something that doesn't look as an error. I'm not sure whether this issue is from lidarr side or your script side. FLACs are normally downloaded, compressed to MP3-320 and moved to recycle. No half-baked tracks, everything's fine. Just this apparently bogus error warning.

**Comment by TheCaptain989** [comment]
This error means that the final Lidarr API call to rescan the artist folders failed.  You still get converted files, but Lidarr just might not reflect the update.  Since you have debug level 2, you can check the flac2mp3.txt log file for full details.  If you post it here I can look it over.

I've found Lidarr's API to be very finicky.  Especially when it comes to string quoting, even for properties.

**Comment by janaxhell** [comment]
Tha pastebin i linked is the log of debug-2 while that happened.

**Comment by TheCaptain989** [comment]
Oh, got it!  Sorry.

Okay, the log just indicates a timeout.  The script only waits 15 seconds for a rescan to complete and then gives up, but you can see that the rescan was triggered.

**Comment by janaxhell** [comment]
Fine, cheers! :)
